### ISSUE TITLE
undefined connection when using plain XMPP client declaration

### ISSUE THREAD

**Issue by danielGz** [samuelagm/nativescript-xmpp-client#4]
I'm getting a "cannot read property 'on' of undefined" error, this is my code:

` var client = new Client({               
               jid: 'danx@nuttin.com',
               password: 'dudaso77'
           });`
by debugging I think I found it relates to this portion of the session.js generated file being commented out:

`Session.prototype._setupSocketConnection = function (opts) {
  var params = {
    xmlns: { '': opts.xmlns },
    streamAttrs: {
      version: '1.0',
      to: this.jid.domain
    },
    serialized: opts.serialized
  } . . . etc`

since Client seems to inherit from Session and that's where the connection object comes from, I'm not sure if this is because of some dependency to an outdated xmpp library, I traced this code back to node-xmpp-client package. If you install it manually using npm you can see the code but seems like the repository no longer exists and leads to xmpp.js [http://github.com/node-xmpp/node-xmpp/](http://github.com/node-xmpp/node-xmpp/)

**Comment by samuelagm** [comment]
Thanks Daniel, I have to overhaul the underlying xmmp library dependency.
I'm working in it at the moment.

**Comment by samuelagm** [comment]
hello danielGz, from your example, I noticed you didn't provide a websocket object  e.g 
`websocket: {url: 'ws://192.168.10.102:5280'},`

Your client config is supposed to look like the example below:
`var client = new Client({
            websocket: {url: 'ws://nuttin.com'},
            jid: 'danx@nuttin.com',
            password: 'dudaso77'
        });`
