### ISSUE TITLE
Don't work with webpack

### ISSUE THREAD

**Issue by acortino** [samuelagm/nativescript-xmpp-client#5]
Hi, 
I'm using your plugin for 6 months now, and everything's great! 
But now I'm trying to bundle my app with Webpack to improve the perfomance, and I have issue with your plugin (again everything's great if I don't bundle it with Webpack)

So, when I launch

`tns run ios --bundle`

This error pops:
`JS ERROR TypeError: undefined is not a constructor (evaluating 'new Stanza(name, attrs)')`

Apparently it's in the StreamParser file of @xmpp lib

**Comment by samuelagm** [comment]
I'll add webpack support ASAP

**Comment by acortino** [comment]
The issue is solved when i run ```npm i``` into node_modules/nativescript-xmpp-client

**Comment by samuelagm** [comment]
What a hack! 👍 , I'm rewriting the plugin with the latest nativescript plugin format, that should give the plugin the webpack support by default.
